name: auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        uses: pascalgn/automerge-action@v0.15.0
        env:
          GITHUB_TOKEN: "${{ secrets.WORKFLOW_TOKEN }}"
