name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check author
        id: check_author
        run: |
          ALLOWED_AUTHORS="rajarshisamaddar soumayadipsaha Soumelee prateekpranveer"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          if [[ $ALLOWED_AUTHORS != *"$PR_AUTHOR"* ]]; then
            echo "Author '$PR_AUTHOR' is not allowed to auto-merge"
            exit 1
          fi
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.WORKFLOW_TOKEN }}"
